# Generated by Django 5.2.4 on 2025-07-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('tradisi', 'Tradisi'), ('makanan', 'Makanan'), ('seni', 'Seni & Budaya'), ('bahasa', 'Bahasa'), ('sejarah', 'Sejarah'), ('umum', 'Umum')], max_length=50),
        ),
    ]
