# Generated by Django 5.2.4 on 2025-07-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_forumpost_options_forumpost_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('Diskusi', 'Diskusi'), ('Pertanyaan', 'Pertanyaan'), ('Berbagi Info', 'Berbagi Info'), ('Event', 'Event'), ('Penelitian', 'Penelitian')], max_length=50),
        ),
    ]
